source:
  kind: kafka
  topicPrefix: debezium.mysql.sakila
  config:
    bootstrap.servers: kafka:9092
    group.id: alluvial
    key.converter: io.confluent.connect.avro.AvroConverter
    value.converter: io.confluent.connect.avro.AvroConverter
    key.converter.schema.registry.url: http://schema-registry:8081
    value.converter.schema.registry.url: http://schema-registry:8081
    poll.timeout.ms: 1000

sink:
  kind: iceberg
  catalog:
    catalog-type: hadoop
    warehouse: /tmp/warehouse
    # warehouse: s3a://alluvial/warehouse
    # catalog-type: hive
    # uri: thrift://hive-metastore:9083
    # io-impl: org.apache.iceberg.aws.s3.S3FileIO
    ## see: org.apache.iceberg.aws.AwsProperties
    # s3.endpoint: http://minio:9000
    # s3.access-key-id: admin
    # s3.secret-access-key: SuperSecr3t
  tableCreation:
    properties:
      write.format.default: AVRO
      write.target-file-size-bytes: 134217728  # 128MB
      # engine.hive.enabled: true
    # baseLocation: s3a://alluvial/sakila/
    partitionSpec:
      # Partitioned by column "actor_id" using "void" transformation
      actor:
        - column: actor_id
          transform: void
      address:
        - column: address_id
          transform: bucket[10]
      category:
        - column: name
          transform: truncate[2]
      city:
        - column: country_id
          transform: identity
      film:
        - column: last_update
          transform: month
      film_actor:
        - column: last_update
          transform: day
      payment:
        - column: last_update
          transform: hour
      # Partitioned by multiple columns
      customer:
        - column: last_update
          transform: year
        - column: first_name
          transform: truncate[2]
        - column: last_name
          transform: bucket[3]
      # Partitioned by multiple columns using the same transformation
      staff:
        - column: first_name
          transform: truncate[2]
        - column: last_name
          transform: truncate[2]

stream:
  kind: debezium
  streamletIdleTimeout: "15m"
  streamletExamineInterval: "3m"
  commitBatchSize: 1000
  commitTimespan: "10m"
