version: '3.7'


services:
  kafka:
    image: bitnami/kafka:3.5
    environment:
      # KRaft settings
      KAFKA_CFG_NODE_ID: 0
      KAFKA_CFG_PROCESS_ROLES: controller,broker
      KAFKA_CFG_CONTROLLER_QUORUM_VOTERS: 0@kafka:9093
      # Listeners
      KAFKA_CFG_LISTENERS: PLAINTEXT://:9092,CONTROLLER://:9093
      KAFKA_CFG_ADVERTISED_LISTENERS: PLAINTEXT://:9092
      KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP: CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT
      KAFKA_CFG_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_CFG_INTER_BROKER_LISTENER_NAME: PLAINTEXT
    hostname: kafka
    networks:
      default:
        ipv4_address: 10.5.0.3
    ports:
      - 9092:9092
    volumes:
      - kafka_data:/bitnami
    healthcheck:
      test:
        [ "CMD", "kafka-topics.sh", "--list", "--bootstrap-server", "localhost:9092" ]

  schema-registry:
    image: bitnami/schema-registry:7.4
    depends_on: [ kafka ]
    environment:
      SCHEMA_REGISTRY_KAFKA_BROKERS: PLAINTEXT://kafka:9092
      SCHEMA_REGISTRY_AVRO_COMPATIBILY_LEVEL: NONE
    networks:
      default:
        ipv4_address: 10.5.0.4
    ports:
      - 8081:8081

  debezium:
    image: alluvial/debezium:2.3
    build:
      context: ./debezium
      args:
        DEBEZIUM_VERSION: 2.3
    depends_on: [ kafka ]
    environment:
      BOOTSTRAP_SERVERS: kafka:9092
      GROUP_ID: 1
      CONFIG_STORAGE_TOPIC: _debezium.configs
      OFFSET_STORAGE_TOPIC: _debezium.offsets
      STATUS_STORAGE_TOPIC: _debezium.statuses
      KEY_CONVERTER: io.confluent.connect.avro.AvroConverter
      VALUE_CONVERTER: io.confluent.connect.avro.AvroConverter
      CONNECT_KEY_CONVERTER_SCHEMA_REGISTRY_URL: http://schema-registry:8081
      CONNECT_VALUE_CONVERTER_SCHEMA_REGISTRY_URL: http://schema-registry:8081

      ENABLE_CONFLUENT_CONVERTERS: true
    networks:
      default:
        ipv4_address: 10.5.0.5
    ports:
      - 8083:8083

  console:
    image: docker.redpanda.com/vectorized/console:v2.3.1
    depends_on: [ kafka, schema-registry ]
    environment:
      CONFIG_FILEPATH: /etc/kafka-console/config.yml
    networks:
      default:
        ipv4_address: 10.5.0.6
    ports:
      - 8080:8080
    volumes:
      - ./console:/etc/kafka-console/

  ##### MySQL #####
  # https://hub.docker.com/_/mysql
  # https://debezium.io/documentation/reference/1.8/connectors/mysql.html#setting-up-mysql
  # Help:
  # $ mysql -u root -p
  # mysql> SHOW VARIABLES LIKE '%gtid%';
  mysql:
    image: mysql:8.0
    command:
      - --gtid-mode=ON
      - --enforce_gtid_consistency=ON
      - --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: SuperSecr3t
    networks:
      default:
        ipv4_address: 10.5.0.7
    ports:
      - 3306:3306
      - 33060:33060
    volumes:
      - ./mysql/:/docker-entrypoint-initdb.d/
      - mysql_data:/var/lib/mysql

  ##### PostgreSQL #####
  # https://hub.docker.com/_/postgres
  # Help:
  # $ psql -U postgres [-W]
  # sql> SHOW wal_level;
  # sql> SELECT * FROM pg_settings;
  postgres:
    image: postgres:15-alpine
    command:
      - -c
      - wal_level=logical
      - -c
      - wal_compression=on
    environment:
      POSTGRES_PASSWORD: SuperSecr3t
    networks:
      default:
        ipv4_address: 10.5.0.8
    ports:
      - 5432:5432
    volumes:
      - ./postgres/:/docker-entrypoint-initdb.d/
      - postgres_data:/var/lib/postgresql/data

volumes:
  kafka_data:
  mysql_data:
  postgres_data:

networks:
  default:
    name: alluvial
    ipam:
      config:
        - subnet: 10.5.0.0/16
