version: '3.7'


services:
  zookeeper:
    image: quay.io/debezium/zookeeper:1.9.3.Final
    networks:
      default:
        ipv4_address: 10.5.0.2
    # ports:
    #   - 2181:2181 # client connections
    #   - 2888:2888 # peers connections
    #   - 3888:3888 # leader election

  kafka:
    image: quay.io/debezium/kafka:1.9.3.Final
    environment:
      ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_NUM_PARTITIONS: 12
    depends_on:
      - zookeeper
    networks:
      default:
        ipv4_address: 10.5.0.3
    ports:
      - 9092:9092
    healthcheck:
      test:
        [ "CMD", "kafka-topics.sh", "--list", "--zookeeper", "zookeeper:2181" ]

  schema-registry:
    image: confluentinc/cp-schema-registry:7.3.0
    container_name: schema-registry-alluvial
    hostname: schema-registry
    environment:
      SCHEMA_REGISTRY_HOST_NAME: schema-registry
      SCHEMA_REGISTRY_KAFKASTORE_BOOTSTRAP_SERVERS: kafka:9092
      SCHEMA_REGISTRY_LISTENERS: http://0.0.0.0:8081
      SCHEMA_REGISTRY_SCHEMA_COMPATIBILITY_LEVEL: NONE
    depends_on:
      - kafka
    networks:
      default:
        ipv4_address: 10.5.0.4
    ports:
      - 8081:8081

  debezium:
    image: alluvial/debezium
    build:
      context: ./debezium

    environment:
      BOOTSTRAP_SERVERS: kafka:9092
      GROUP_ID: 1
      CONFIG_STORAGE_TOPIC: _debezium.configs
      OFFSET_STORAGE_TOPIC: _debezium.offsets
      STATUS_STORAGE_TOPIC: _debezium.statuses
      KEY_CONVERTER: io.confluent.connect.avro.AvroConverter
      VALUE_CONVERTER: io.confluent.connect.avro.AvroConverter
      CONNECT_KEY_CONVERTER_SCHEMA_REGISTRY_URL: http://schema-registry:8081
      CONNECT_VALUE_CONVERTER_SCHEMA_REGISTRY_URL: http://schema-registry:8081
    depends_on:
      - kafka
    networks:
      default:
        ipv4_address: 10.5.0.5
    ports:
      - 8083:8083

  akhq:
    image: tchiotludo/akhq:0.20.0
    environment:
      MICRONAUT_CONFIG_FILES: /etc/akhq/akhq.yml
    volumes:
      - ./akhq.yml:/etc/akhq/akhq.yml
    networks:
      default:
        ipv4_address: 10.5.0.6
    ports:
      - 8080:8080

  ##### MySQL #####
  # https://hub.docker.com/_/mysql
  # https://debezium.io/documentation/reference/1.8/connectors/mysql.html#setting-up-mysql
  # Help:
  # $ mysql -u root -p
  # mysql> SHOW VARIABLES LIKE '%gtid%';
  mysql:
    image: mysql:8.0
    command:
      - --gtid-mode=ON
      - --enforce_gtid_consistency=ON
      - --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: SuperSecr3t
    networks:
      default:
        ipv4_address: 10.5.0.7
    ports:
      - 3306:3306
      - 33060:33060
    volumes:
      - ./mysql/:/docker-entrypoint-initdb.d/
      - mysql_data:/var/lib/mysql

  ##### PostgreSQL #####
  # https://hub.docker.com/_/postgres
  # Help:
  # $ psql -U postgres [-W]
  # sql> SHOW wal_level;
  # sql> SELECT * FROM pg_settings;
  postgres:
    image: postgres:11-alpine
    command:
      - -c
      - wal_level=logical
      - -c
      - wal_compression=on
    environment:
      POSTGRES_PASSWORD: SuperSecr3t
    networks:
      default:
        ipv4_address: 10.5.0.8
    ports:
      - 5432:5432
    volumes:
      - ./postgres/:/docker-entrypoint-initdb.d/
      - postgres_data:/var/lib/postgresql/data

volumes:
  mysql_data:
  postgres_data:

networks:
  default:
    name: alluvial
    ipam:
      config:
        - subnet: 10.5.0.0/16
