---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "alluvial.fullname" . }}
  labels:
    {{- include "alluvial.labels" . | nindent 4 }}
data:
  config.yaml: |
    {{- toYaml .Values.configs | nindent 4 }}
