---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "alluvial.fullname" . }}
  labels:
    {{- include "alluvial.labels" . | nindent 4 }}
data:
  config.yaml: |
    {{- toYaml .Values.configs | nindent 4 }}

  logback.xml: |
    <configuration>
      <variable scope="context" name="telemetry"
                value="%replace(%prefix(%X{trace_id} %X{span_id})){'\\S+=(\\s+|$)', ''}"/>

      <appender name="CONSOLE" class="ch.qos.logback.core.ConsoleAppender">
        <encoder>
          <!-- ISO-8601 format: https://jira.qos.ch/browse/LOGBACK-262 -->
          <!-- https://logback.qos.ch/manual/layouts.html -->
          <pattern>
            %date{"yyyy-MM-dd'T'HH:mm:ss,SSSXXX", UTC} %highlight(%-5level) %logger{25} [%boldGreen(%X{name:-*})] ${telemetry} - %message%n
          </pattern>
        </encoder>
      </appender>

      <!-- Just wrap your logging appender, for example ConsoleAppender, with OpenTelemetryAppender -->
      <appender name="OTEL" class="io.opentelemetry.instrumentation.logback.mdc.v1_0.OpenTelemetryAppender">
        <appender-ref ref="CONSOLE"/>
      </appender>

      <root level="INFO">
        <appender-ref ref="OTEL"/>
      </root>

      {{- range $key, $value := omit .Values.logging "ROOT" }}
      <logger name="{{ $key }}" level="{{ $value }}"/>
      {{- end }}
    </configuration>
